// Glossaire enrichi V6 — 65 termes
module.exports = [
  {t:"GWP",c:"Sigle",d:"Global Warming Potential. Impact climatique sur 100 ans vs CO₂ (ref=1). Ex: R134a = 1430."},
  {t:"ODP",c:"Sigle",d:"Ozone Depletion Potential. Impact sur couche d'ozone. HFC = 0."},
  {t:"HFC",c:"Fluide",d:"Hydrofluorocarbures. Sans chlore (ODP=0), fort GWP. Ex: R134a, R410A. Soumis à quotas."},
  {t:"tCO₂e",c:"Unité",d:"Tonnes équivalent CO₂. Calcul: tCO₂e = (Charge kg × GWP) / 1000. Détermine les obligations."},
  {t:"Phase-down",c:"Réglementation",d:"Réduction progressive quotas HFC dans l'UE. Objectif: -85% en 2030 vs 2015."},
  {t:"Attestation d'aptitude",c:"Certification",d:"Certificat obligatoire manipulation fluides. Cat I (tous), II (<2kg), III (<3kg). Remise à niveau 7 ans."},
  {t:"Attestation de capacité",c:"Certification",d:"Certificat obligatoire pour l'entreprise. Délivré par un organisme agréé. Conditionne le droit d'intervenir."},
  {t:"Registre",c:"Traçabilité",d:"Document obligatoire: toutes interventions. Conservation 5 ans après mise hors service."},
  {t:"Fuite",c:"Technique",d:"Perte non intentionnelle de fluide. Réparation sous 14 jours. Détection auto ≥500 tCO₂e."},
  {t:"Récupération",c:"Pratique",d:"Extraction fluide vers bouteille. Obligatoire avant intervention majeure et fin de vie."},
  {t:"Tirage au vide",c:"Technique",d:"Évacuation air+humidité du circuit. Pompe à vide, objectif <1 mbar, durée min 30 min."},
  {t:"Compresseur",c:"Organe",d:"Comprime gaz BP → gaz HP haute température. Cœur du circuit frigorifique."},
  {t:"Condenseur",c:"Organe",d:"Échangeur: gaz HP → liquide HP en cédant chaleur au milieu extérieur."},
  {t:"Détendeur",c:"Organe",d:"Laminage: liquide HP → BP. Transformation isenthalpique. Sortie: mélange liq-vapeur BP."},
  {t:"Évaporateur",c:"Organe",d:"Échangeur: liquide BP → gaz BP en absorbant chaleur = production du froid."},
  {t:"Surchauffe",c:"Paramètre",d:"T° aspiration − T° évaporation saturée. Garantit que seul du gaz entre au compresseur."},
  {t:"Sous-refroidissement",c:"Paramètre",d:"T° condensation saturée − T° liquide sortie condenseur. Augmente puissance frigorifique."},
  {t:"Charge en fluide",c:"Pratique",d:"Introduction fluide dans circuit. Phase liquide (HP) ou gazeuse (BP) selon type. Balance précision."},
  {t:"Zéotrope",c:"Fluide",d:"Mélange avec glissement de T°. Ex: R407C (glissement 7°C). Charge liquide uniquement."},
  {t:"Azéotrope",c:"Fluide",d:"Mélange ≈ corps pur. Ex: R410A (glissement <0,2°C). Charge liquide ou gaz."},
  {t:"R134a",c:"Fluide",d:"HFC pur, GWP 1430. Clim auto et commercial. Pression modérée, huile POE. Quotas."},
  {t:"R410A",c:"Fluide",d:"Mélange quasi-azéotrope (R32+R125), GWP 2088. Clim résidentiel. Hautes pressions. POE."},
  {t:"R32",c:"Fluide",d:"HFC pur, GWP 675. Alternative R410A. Légèrement inflammable A2L. PAC réversibles."},
  {t:"R290",c:"Fluide",d:"Propane naturel, GWP 3. Très inflammable A3. Charges limitées. Réfrigération commerciale."},
  {t:"R744",c:"Fluide",d:"CO₂ naturel, GWP 1. Non toxique, non inflammable. Très hautes pressions >100 bar. Transcritique."},
  {t:"R717",c:"Fluide",d:"Ammoniac NH₃ naturel, GWP <1. Toxique (B). Froid industriel. Détection obligatoire."},
  {t:"COP",c:"Performance",d:"Coefficient Of Performance = P thermique / P électrique. Ex: COP 4 = 4 kW therm / 1 kW élec."},
  {t:"EER",c:"Performance",d:"Energy Efficiency Ratio = P froid / P élec. Version saisonnière: SEER. A+++ = EER > 3,6."},
  {t:"CERFA",c:"Document",d:"Formulaire administratif officiel. CERFA 15497*04 pour les fiches d'intervention sur équipements contenant des fluides."},
  {t:"BSD",c:"Document",d:"Bordereau de Suivi des Déchets. Document traçant le transport et le traitement des fluides récupérés."},
  {t:"FDS",c:"Document",d:"Fiche de Données de Sécurité. 16 rubriques obligatoires. Fournie par le fabricant du fluide."},
  {t:"ADEME",c:"Organisme",d:"Agence de l'Environnement et de la Maîtrise de l'Énergie. Déclarations annuelles des opérateurs."},
  {t:"EN 378",c:"Norme",d:"Norme européenne sur les systèmes de réfrigération. Définit charges maximales, ventilation, classification locaux."},
  {t:"TEWI",c:"Indicateur",d:"Total Equivalent Warming Impact. Somme des émissions directes (fuites) + indirectes (énergie) sur la durée de vie."},
  {t:"A1",c:"Classification",d:"Classe de sécurité ISO 817: non inflammable, faible toxicité. Ex: R134a, R404A, R410A."},
  {t:"A2L",c:"Classification",d:"Classe de sécurité: légèrement inflammable, faible toxicité. Ex: R32, R1234yf. Vitesse de flamme <10 cm/s."},
  {t:"A3",c:"Classification",d:"Classe de sécurité: très inflammable, faible toxicité. Ex: R290 (propane), R600a (isobutane)."},
  {t:"B2L",c:"Classification",d:"Classe de sécurité: légèrement inflammable, toxicité plus élevée. Ex: R717 (NH₃)."},
  {t:"CFC",c:"Fluide",d:"Chlorofluorocarbures. Interdits (Montréal 1987). ODP élevé. Ex: R12, R11. Plus utilisés."},
  {t:"HCFC",c:"Fluide",d:"Hydrochlorofluorocarbures. Interdits depuis 2015 (UE). ODP faible. Ex: R22."},
  {t:"HFO",c:"Fluide",d:"Hydrofluoro-oléfines. GWP très bas (<10). Ex: R1234yf (GWP 4), R1234ze. Instables dans l'atmosphère."},
  {t:"Drop-in",c:"Substitution",d:"Remplacement direct d'un fluide par un autre sans modifier l'installation. Rare en pratique stricte."},
  {t:"Retrofit",c:"Substitution",d:"Remplacement d'un fluide nécessitant des modifications mineures (huile, détendeur, réglages)."},
  {t:"Glissement",c:"Thermodynamique",d:"Différence entre T° de rosée et T° de bulle d'un mélange zéotrope. Ex: R407C = 7°C de glissement."},
  {t:"Pression de service",c:"Technique",d:"Pression maximale admissible en fonctionnement normal. Inscrite sur la plaque signalétique."},
  {t:"Charge maximale",c:"Réglementation",d:"Quantité max de fluide autorisée dans un local. Dépend de la classe de sécurité et du volume (EN 378)."},
  {t:"Ventilation",c:"Sécurité",d:"Obligation de ventilation des locaux techniques selon EN 378. Naturelle ou mécanique selon le fluide."},
  {t:"ATEX",c:"Sécurité",d:"ATmosphères EXplosives. Zones classées selon risque d'explosion. Concerne R290, R600a et autres A3."},
  {t:"POI",c:"Sécurité",d:"Plan d'Organisation Interne. Document de gestion des urgences dans les installations industrielles."},
  {t:"Consignation",c:"Sécurité",d:"Procédure de mise en sécurité d'un équipement avant intervention. Électrique, mécanique, fluidique."},
  {t:"Brasage",c:"Pratique",d:"Assemblage de tubes cuivre par fusion d'un métal d'apport. Toujours sous flux d'azote pour éviter l'oxydation."},
  {t:"Azote",c:"Pratique",d:"Gaz inerte utilisé pour le balayage (brasage), l'épreuve de résistance et la recherche de fuites (pression)."},
  {t:"Déshydrateur",c:"Composant",d:"Filtre contenant un dessicant (tamis moléculaire) pour absorber l'humidité résiduelle du circuit."},
  {t:"Voyant liquide",c:"Composant",d:"Hublot sur la ligne liquide. Bulle = manque de charge ou SR insuffisant. Pastille = taux d'humidité."},
  {t:"Pressostat",c:"Composant",d:"Capteur/interrupteur à pression. HP: sécurité haute pression. BP: régulation ou sécurité basse pression."},
  {t:"Bouteille de récupération",c:"Équipement",d:"Récipient pour stocker le fluide récupéré. Grise à collerette jaune. Remplissage max 80%."},
  {t:"Pompe à vide",c:"Équipement",d:"Appareil pour évacuer l'air et l'humidité du circuit. Objectif: vide < 500 µm (0,5 mbar)."},
  {t:"Manomètre",c:"Équipement",d:"Instrument de mesure de pression. Bleu = BP, Rouge = HP. Lecture en bar et correspondance T° saturée."},
  {t:"Balance de charge",c:"Équipement",d:"Balance de précision (±5g) pour peser le fluide lors de la charge ou récupération."},
  {t:"Détecteur de fuites",c:"Équipement",d:"Appareil électronique pour localiser les fuites. Sensibilité min 5 g/an. Calibration annuelle."},
  {t:"Diagramme de Mollier",c:"Thermodynamique",d:"Diagramme enthalpie-pression (log P / h). Représente le cycle frigorifique et les états du fluide."},
  {t:"Enthalpie",c:"Thermodynamique",d:"Énergie totale d'un fluide (kJ/kg). Sur le diagramme de Mollier: axe horizontal."},
  {t:"Isenthalpique",c:"Thermodynamique",d:"Transformation à enthalpie constante. C'est le cas de la détente (pas d'échange de chaleur)."},
  {t:"Titre",c:"Thermodynamique",d:"Proportion de vapeur dans un mélange liquide-vapeur. x=0: tout liquide. x=1: tout vapeur."},
  {t:"Protocole de Montréal",c:"Réglementation",d:"Traité international (1987) visant l'élimination des substances appauvrissant la couche d'ozone (CFC, HCFC)."},
];
